### ISSUE TITLE
Phonons.Phonons does not support ibrav!=0

### ISSUE THREAD

**Issue by gjoalland13** [SSCHAcode/CellConstructor#93]
An error is raised when opening the attached dynamical matrix, for which the `ibrav=-12` when using the following code:
```
import cellconstructor as CC
HARM_DYN = "path/to/dynamical-matrix-"
NQIRR = 8

harmonic_dyn = CC.Phonons.Phonons(HARM_DYN, NQIRR)
```
The following issue is raised:
```
Traceback (most recent call last):
  File "/home/gjoalland/work/WO3/jupyter/phonon/plot_phonons.py", line 47, in <module>
    harmonic_dyn = CC.Phonons.Phonons(HARM_DYN, NQIRR)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gjoalland/work/.venv-aiida/lib/python3.11/site-packages/cellconstructor/Phonons.py", line 126, in __init__
    self.LoadFromQE(structure, nqirr, full_name = full_name, use_format = use_format)
  File "/home/gjoalland/work/.venv-aiida/lib/python3.11/site-packages/cellconstructor/Phonons.py", line 241, in LoadFromQE
    unit_cell = Methods.get_unit_cell_from_ibrav(ibrav, celldm)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gjoalland/work/.venv-aiida/lib/python3.11/site-packages/cellconstructor/Methods.py", line 904, in get_unit_cell_from_ibrav
    raise ValueError("Error, the specified ibrav %d is not supported." % ibrav)
ValueError: Error, the specified ibrav -11 is not supported.
```
[dynamical-matrix-1.txt](https://github.com/SSCHAcode/CellConstructor/files/14979058/dynamical-matrix-1.txt)

**Comment by mesonepigreco** [comment]
Ok, two errors found in the implementation of ``get_unit_cell_from_ibrav``.
First, ibrav -12 is not implemented.
Second there is a rounding to ibrav that does not work for negative numbers ``int(ibrav + .5)``, that transforms -12 to -11
